### ISSUE TITLE
BULK SMS API Service Intergration

### ISSUE THREAD

**Issue by paulwababu** [myckhel/church-management-system#55]
How do i intergrate the bulk SMS Service? 
My live API is 
Make a GET request to:
https://alienx.tech/api/v1/sms/?text=YOURMESSAGE&number=KENYANNUMER

**Comment by paulwababu** [comment]
Or how should a sample payload look like in order to successfully intergrate the callback with your system? Thank you sir. Beautiful work btw!

**Comment by myckhel** [comment]
Unfortunately the sms system was not developed in a dynamic way. it only assumes your sms api accepts `message` instead of `text` and `recipient` instead of `number`.

The sms system should be redeveloped for it to be used dynamically.

## Workaround
Ill suggest u modify this line of code https://github.com/myckhel/church-management-system/blob/96a2d9067c39fd7e2a058c0791d4a17cce9c43df/app/Http/Controllers/MessagingController.php#L65
and change `message` to `text` and `recipient` to `number`.

**Comment by paulwababu** [comment]
Thank you man!

**Comment by paulwababu** [comment]
Could i leave out the credential key?

**Comment by myckhel** [comment]
yes. it was just an example request query

**Comment by paulwababu** [comment]
sorry, and where is the url for the sms balance api controller to check balance? I cant seem to find it, thanks

**Comment by myckhel** [comment]
You should see the balance from this page `messaging/sms` if url set properly
